[lib][stdio] wrap file io APIs with stdio APIs
littlekernel/lk pull request #340
Opened 2022-08-04 05:53 UTC by chiehmin

Implement stdio file io APIs with LK lib/fs APIs

Signed-off-by: Chieh-Min Wang <cmwang@google.com>

2022-08-05 18:29 UTC, travisg commented
Oh I like this! I'll need to think about it a little bit since there are two (minor) issues I'd like to consider:

1) this CL will force lib/fs to always be built in all configurations, even in situations where fses aren't really needed (deeply embedded stuff). If it could be made to be conditional if lib/fs is present that might be helpful, though that can be a bit messy in the header space.
2) the switch between using an io_handle_t and a filehandle is a little clumsy. Perhaps it'd make a bit more sense to extend io_handle_t to wrap a file? or even union the two in the FILE so that it's a bit more obvious it's one or the other? I don't know of all of the downstream users of io_handle_t but i suspect there are more than just what's in the tree, so it might be a bit better to test on something ike filehandle being non-null, or store a bool or flag that says which one is active.

For 1 it *is* possoble to test for the presence of another module by testing for WITH_LIB_FS, though it might be a bit nasty ifdef wise.

2022-08-06 16:42 UTC, chiehmin commented
@travisg I have push a new commit to fix the issues you mentioned. Please take a look at it to see if it matches your expection. Thanks! 😄

2022-08-15 02:18 UTC, travisg commented
Looks pretty good! I might fiddle with it a bit, but I think I can take it as is!

2022-08-15 02:23 UTC, travisg commented on app/tests/stdio_file_tests.c
> +        printf("fwrite size mismatched. wsize = %d, content_len = %d\n", wsize, content_len);
%d needs to be %zu since it's a size_t. Fails on various architectures.

2022-08-15 02:30 UTC, travisg requested changes

2022-08-15 02:30 UTC, travisg commented on app/tests/tests.c
> +#ifdef WITH_LIB_FS
here and elsewhere, can you replace this with #if instead of #ifdef? There's a convention in the code for using it that way.

2022-08-15 02:30 UTC, travisg commented on lib/libc/stdio.c
> +#ifdef WITH_LIB_FS
Can probably optimize this a bit to just wrap around the .use_fs line to avoid as much copying of code.

2022-08-15 02:30 UTC, travisg commented on lib/libc/stdio.c
> +#ifdef WITH_LIB_FS
This will probably be a little cleaner to reorder such that the io_read part is the same, but it jsut #ifs in the (stream->use_fs) { } part.

2022-08-15 02:30 UTC, travisg commented on lib/libc/stdio.c
> +static inline int clamp(int val, int min, int max) {
These types probably should be off_t which is i believe 64bit in 64bit arches.

2022-08-15 02:30 UTC, travisg commented on lib/libc/stdio.c
> +
might be worth adding an error check for size < 1, since that should be impossible to fill in a string.

2022-08-15 02:37 UTC, travisg commented on app/tests/stdio_file_tests.c
> +#ifdef WITH_LIB_FS
Since this logically belongs to lib/fs can you move this over into lib/fs/test.c and if possible use the lib/unittest framework?

2022-08-15 05:01 UTC, chiehmin commented
@travisg I have resolved all the comments and updated this PR. Please give another review of it. Thanks!

2022-08-19 01:51 UTC, chiehmin commented on lib/libc/stdio.c
> +    return (ret > 0) ? c : -1;
This is a fix for incorrect EOF handling

2022-08-26 07:42 UTC, chiehmin commented
@travisg Is there other considerations for this CL?

2022-09-05 02:02 UTC, chiehmin commented
@travisg Any update 😃 ?

2022-09-06 04:48 UTC, travisg commented
Not yet, haven't had a chance to run it.

2022-09-14 05:51 UTC, travisg commented
Just want to comment that I haven't forgotten about this, just have been really busy the last few weeks. Currently on a business trip out of country.

2022-10-19 06:24 UTC, chiehmin commented
@travisg Any update for this 😃 ?

2024-04-18 06:58 UTC, travisg commented
looks good! apologize for waiting so long, but i'm generally back on LK nowadays and have been going through backlog.

2024-04-18 06:59 UTC, merged