[console] support background command execution
littlekernel/lk pull request #404
Opened 2024-04-29 07:55 UTC by chiehmin

Launch a thread to execute commands when the last argument is ampersand

2025-06-12 02:18 UTC, chiehmin commented
@travisg Ping. Do you mind take a look at this? Thank you!

2025-06-12 02:19 UTC, travisg commented
Will do!

2025-07-04 06:14 UTC, chiehmin commented
@travisg Any chances to take a look?

2025-07-10 02:33 UTC, travisg commented on lib/console/console.c
> +            con->lastresult = thread_resume(thr);
suggestion: make this thread_detach_and_resume, instead of thread_resume. This allows it to exit on its own, without requiring the original thread needing to thread_join() it.

2025-07-10 02:35 UTC, travisg requested changes
Looks pretty good, only suggestion is switching from thread_resume to thread_detach_and_resume.

2025-07-10 02:49 UTC, closed without merging

2025-07-10 02:52 UTC, chiehmin commented
Sorry, the PR was closed due to a accidental force push. 

The new PR is at https://github.com/littlekernel/lk/pull/449